In [ ]:
import numpy as np
players_stats = np.array([[5,56,120],[6,56,89],[7,65,430],[4,80,75]])
print(players_stats)
max_points = np.argmax(players_stats[:,2])
players_stats[max_points,1] = 220
print(players_stats)


[[  5  56 120]
 [  6  56  89]
 [  7  65 430]
 [  4  80  75]]
[[  5  56 120]
 [  6  56  89]
 [  7 220 430]
 [  4  80  75]]


In [9]:
new_player = np.array([[6,45,300]])
players_stats = np.vstack((players_stats,new_player))
print(players_stats)

[[  5  56 120]
 [  6  56  89]
 [  7 220 430]
 [  4  80  75]
 [  6  45 300]
 [  6  45 300]]


In [10]:
new_stat = np.array([[80,190,35]])
players_stats = np.insert(players_stats,2,new_stat,axis=0)
print(players_stats)

[[  5  56 120]
 [  6  56  89]
 [ 80 190  35]
 [  7 220 430]
 [  4  80  75]
 [  6  45 300]
 [  6  45 300]]


In [11]:
min_points = np.argmin(players_stats[:,2])
players_stats = np.delete(players_stats,min_points,axis=0)
print(players_stats)

[[  5  56 120]
 [  6  56  89]
 [  7 220 430]
 [  4  80  75]
 [  6  45 300]
 [  6  45 300]]


In [12]:
arr1 = np.array([[56,120],[56,89],[65,430],[80,75]])
arr2 = np.array([[34,78],[56,98],[87,23],[45,76]])
print(arr1)
print(arr2)

[[ 56 120]
 [ 56  89]
 [ 65 430]
 [ 80  75]]
[[34 78]
 [56 98]
 [87 23]
 [45 76]]


In [13]:
shallow = arr1.view()
deep = np.copy(arr2)
print(shallow)
print(deep)

[[ 56 120]
 [ 56  89]
 [ 65 430]
 [ 80  75]]
[[34 78]
 [56 98]
 [87 23]
 [45 76]]


In [14]:
concatenated_array = np.concatenate((arr1,arr2),axis=0)
print(concatenated_array)

[[ 56 120]
 [ 56  89]
 [ 65 430]
 [ 80  75]
 [ 34  78]
 [ 56  98]
 [ 87  23]
 [ 45  76]]


In [16]:
condition = concatenated_array > 60
arr3 = concatenated_array[condition]
arr4 = concatenated_array[~condition]
print(arr3)
print(arr4)

[120  89  65 430  80  75  78  98  87  76]
[56 56 34 56 23 45]


In [17]:
arr1[1]=[30,40]
arr2[2]=[50,60]
shallow1 = arr1.view()
deep1 = np.copy(arr2)
print(shallow1)
print(deep1)

[[ 56 120]
 [ 30  40]
 [ 65 430]
 [ 80  75]]
[[34 78]
 [56 98]
 [50 60]
 [45 76]]
