In [8]:
import numpy as np

arr = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
arr1 = np.reshape(arr,(4,5))
print(arr1)
arr1[:,-1]=0
print(arr1)
flat = arr1.flatten()
print(flat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  0]
 [ 6  7  8  9  0]
 [11 12 13 14  0]
 [16 17 18 19  0]]
[ 1  2  3  4  0  6  7  8  9  0 11 12 13 14  0 16 17 18 19  0]


In [11]:
import numpy as np

arr = np.random.randint(10, 51, size=(5, 5))
print(arr)

for i in range(arr.shape[0]):
    print(f"Row {i+1}:")
    print(f"Mean: {np.mean(arr[i])}")
    print(f"Sum: {np.sum(arr[i])}")
    print(f"Min: {np.min(arr[i])}")
    print(f"Max: {np.max(arr[i])}")
print()

for i in range(arr.shape[1]):
    print(f"Column {i+1}:")
    print(f"Mean: {np.mean(arr[:, i])}")
    print(f"Sum: {np.sum(arr[:, i])}")
    print(f"Min: {np.min(arr[:, i])}")
    print(f"Max: {np.max(arr[:, i])}")



[[11 21 49 40 11]
 [37 24 44 48 13]
 [37 18 49 12 42]
 [48 26 18 10 39]
 [19 43 50 48 44]]
Row 1:
Mean: 26.4
Sum: 132
Min: 11
Max: 49
Row 2:
Mean: 33.2
Sum: 166
Min: 13
Max: 48
Row 3:
Mean: 31.6
Sum: 158
Min: 12
Max: 49
Row 4:
Mean: 28.2
Sum: 141
Min: 10
Max: 48
Row 5:
Mean: 40.8
Sum: 204
Min: 19
Max: 50

Column 1:
Mean: 30.4
Sum: 152
Min: 11
Max: 48
Column 2:
Mean: 26.4
Sum: 132
Min: 18
Max: 43
Column 3:
Mean: 42.0
Sum: 210
Min: 18
Max: 50
Column 4:
Mean: 31.6
Sum: 158
Min: 10
Max: 48
Column 5:
Mean: 29.8
Sum: 149
Min: 11
Max: 44


In [18]:
import numpy as np

arr = np.identity(4)
print(arr)

arrD5=np.diag(np.diag(arr) + 5)
print(arrD5)

arrD5[-1,:]=1
print(arrD5)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[6. 0. 0. 0.]
 [0. 6. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 6.]]
[[6. 0. 0. 0.]
 [0. 6. 0. 0.]
 [0. 0. 6. 0.]
 [1. 1. 1. 1.]]


In [22]:
import numpy as np

arr = np.random.randint(0,21,size=15)
print(arr)

unique,counts = np.unique(arr,return_counts = True)
print(unique)
print(counts)

indices = []
for i in range(len(unique)):
    if unique[i]>10:
        indices.append(i)
print(indices)
        


[13  7  3  3  6  9 11 11 10  0  8 11  9 10  2]
[ 0  2  3  6  7  8  9 10 11 13]
[1 1 2 1 1 1 2 2 3 1]
[8, 9]


In [21]:
import numpy as np

arr = np.random.rand(3,4)
print(arr)
rounded = np.round(arr,2)
print(rounded)
rounded[:,1]=0.5
print(rounded)

[[0.58255868 0.14417867 0.02155485 0.8454482 ]
 [0.25848527 0.27342198 0.01209697 0.77022084]
 [0.93501978 0.8589556  0.14925417 0.70225334]]
[[0.58 0.14 0.02 0.85]
 [0.26 0.27 0.01 0.77]
 [0.94 0.86 0.15 0.7 ]]
[[0.58 0.5  0.02 0.85]
 [0.26 0.5  0.01 0.77]
 [0.94 0.5  0.15 0.7 ]]
